### ISSUE TITLE
Local datasets and international transport

### ISSUE THREAD

**Issue by michieldenhaan** [quintel/etsource#1452] opened 2017-11-24 12:40 UTC
In local datasets, the international transport allocation sliders currently add a scaled amount of energy to the scenario. For example in Groningen:

![inttrans](https://user-images.githubusercontent.com/32056448/33210937-758e65ba-d11c-11e7-81c6-579cd106745c.png)

CO2 emissions in 1990, on the other hand, are not scaled. The full NL 1990 value is added to the local dataset:

![co21990](https://user-images.githubusercontent.com/32056448/33210943-7b9162f0-d11c-11e7-8466-1d10ccfeba61.png)

**Comment by michieldenhaan** [comment] 2017-11-24 12:48
The second one (total NL CO2 emissions) is intended behaviour, but the first one (scaled energy) is not. Users should be able to allocate the full NL international transport energy consumption to a local dataset.

**Comment by antw** [comment] 2017-11-24 12:56
The problem is that demand is assigned to the aviation and shipping nodes using the `total_demand` nodes. *Those* demands are scaled with respect to the size of the region. I expect that they'll have to be given a custom value using initializer methods/inputs.

**Comment by ChaelKruip** [comment] 2017-11-24 13:12
> I expect that they'll have to be given a custom value using initializer methods/inputs.

Could they be exempt from scaling based on their node group (bunkers)?

**Comment by antw** [comment] 2017-11-24 14:00
> Could they be exempt

If we were going to do that, I'd prefer it be with a `scaling_except = true` attribute in the affected nodes (or something along those lines) rather than having a "magic" hard-coded group.

**Comment by ChaelKruip** [comment] 2017-11-24 14:06
> If we were going to do that, I'd prefer it be with a scaling_except = true attribute in the affected nodes (or something along those lines) rather than having a "magic" hard-coded group.

I agree that it makes sense to explicitly exclude them from scaling. 👍

**Comment by marliekeverweij** [comment] 2018-01-08 15:51
This issue still needs to be fixed :)

Just discussed with @michieldenhaan and @jorisberkhout about it and we are in favour of this solution: 
>If we were going to do that, I'd prefer it be with a scaling_exempt = true attribute in the affected nodes (or something along those lines) rather than having a "magic" hard-coded group.

This `scaling_exempt = true` attribute is not yet used/working right? How long would it take to implement this, @antw? And does this mean that in all other nodes need to have a `scaling_exempt = false` attribute?

**Comment by antw** [comment] 2018-01-08 16:09
> How long would it take to implement this, @antw?

I would guess a day or two.

> And does this mean that all other nodes need to have a scaling_exempt = false attribute?

Other nodes would not need to be explicitly set to `false`; we would use that as the default.

**Comment by marliekeverweij** [comment] 2018-01-15 16:02
> I would guess a day or two.

During the team meeting this afternoon we have decided that we would really like you to implement this :) When would you have time for this, @antw?

**Comment by michieldenhaan** [comment] 2018-02-12 11:00
@antw Do you have time to implement this before the deploy? If not, we may want to consider:

> they'll have to be given a custom value using initializer methods/inputs.

**Comment by antw** [comment] 2018-02-12 11:16
> @antw Do you have time to implement this before the deploy?

I expect so; I'll try to take a look at it this week.

**Comment by antw** [comment] 2018-02-15 14:34
Whoops. I'll reopen this because it isn't fixed until the new Atlas revision is included in ETSource and ETEngine. I'll sort that out today.

**Closed** 2018-02-15 16:36 UTC
